# NOTE(ptrottier): To use this configuration, drop the OpenAPI yaml spec you want to generate from into do_not_submit/spec.yaml.
generatorName: csharp-unity
outputDir: ./generated-v2
inputSpec: do_not_submit/spec.yaml
packageName: com.unity.services.qos
additionalProperties:
  unityVersion: "2020.3"
  packageVersion: "1.3.0"
  unityPackageNamespace: "Unity.Services.Qos.V2"
  unityServiceName: "QosDiscovery"
  generateMarkdownDocumentation: false
  usePhpStyleQueryParams: false
  unityPackageDescription: "Provides connectivity Quality of Service (QoS) measurements from Unity game clients to different Unity game services running in various geographic regions."
  useUnityAuthentication: true
  publicAccess: []
x-recipeEngine:
    moveGeneratorFiles: true
    trackedDir: ./Packages/Public/com.unity.services.qos
    preProcessCommands:
        - echo "Done executing pre process commands."
    postProcessCommands:
        - rm openapi-generator.log
        - rm ./generated-v2/com.unity.services.qos/CHANGELOG.md  # the generated changelog seems broken.
        - echo 'todo update this file' >> ../CHANGELOG.md
        - mkdir -p ../Runtime/v2
        - cp -r ./generated-v2/com.unity.services.qos/Runtime/* ../Runtime/v2/
        - rm -r ./generated-v2
        - echo "Done executing post process commands."
